# Generated by Django 3.0.5 on 2020-12-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Genres'),
        ),
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фильм'), (2, 'Книга'), (3, 'Музыка')]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.PositiveSmallIntegerField(choices=[(1, 'movie'), (2, 'book'), (3, 'music')]),
        ),
    ]
